apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-1
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-1
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keystore-claim
  annotations:  # comment line if you want to use a StorageClass
    # or specify which StorageClass
    volume.beta.kubernetes.io/storage-class: ""   # comment line if you
    # want to use a StorageClass or specify which StorageClass
  labels:
    app: gameon
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
