---
apiVersion: v1
kind: Service
metadata:
  name: javaroom
  labels:
    app: gameon
spec:
  ports:
    - port: 9080
      protocol: TCP
      targetPort: 9080
  selector:
    app: gameon
    tier: javaroom
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: javaroom
  labels:
    app: gameon
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gameon
        tier: javaroom
    spec:
      containers:
        - image: anthonyamanse/sample-room-java:2.0
          name: javaroom
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: keystore
              mountPath: >-
                /opt/ibm/wlp/usr/servers/defaultServer/resources/security
      volumes:
        - name: keystore
          persistentVolumeClaim:
            claimName: keystore-claim
