---
apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    app: gameon
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31200
  selector:
    app: gameon
    tier: controller
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: controller
  labels:
    app: gameon
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gameon
        tier: controller
    spec:
      containers:
        - image: amalgam8/a8-controller
          name: controller
          env:
            - name: A8_LOG_LEVEL
              value: info
            - name: A8_DATABASE_TYPE
              value: redis
            - name: A8_DATABASE_HOST
              value: redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT)
          ports:
            - containerPort: 8080
              name: controller
