---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: gameon
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31300
  selector:
    app: gameon
    tier: registry
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  labels:
    app: gameon
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gameon
        tier: registry
    spec:
      containers:
        - image: amalgam8/a8-registry
          name: registry
          env:
            - name: A8_STORE
              value: redis
            - name: A8_STORE_ADDRESS
              value: $(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT)
          ports:
            - containerPort: 8080
              name: registry
